version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cuda_python_countainer
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - .:/home/gnn
    working_dir: /home/gnn
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
